[project]
name = "py-ts-exploration-template"
version = "0.1.0"
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]

[tool.uv]
required-version = "0.7.3"
