name: "install-python-deps"
description: |
  # install-python-deps

  Use to install pyproject.toml dependencies for use inside Github actions.
  This is not used to install runtime dependencies for building the deploy
  artifact. As such, dev dependencies are installed.

runs:
  using: composite
  steps:
  - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
    with:
      enable-cache: true
  - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    with:
      python-version-file: "pyproject.toml"
  - shell: bash
    run: uv sync --dev --frozen
