name: "CI"
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check-uv-lock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/python-deps
    - run: uv lock --check
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/python-deps
    - run: uv run ruff check
  lint-ts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/ts-deps
    - run: pnpm oxlint
  lint-github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/python-deps
    - run: uv run zizmor --min-severity=high --no-progress .github

  format-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/python-deps
    - run: uv run ruff check --select I --fix
    - run: uv run ruff format --check
  format-ts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/ts-deps
    - run: pnpm dprint check '**/*.{ts,tsx}'
  format-other:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/ts-deps
    - run: pnpm dprint check --excludes '**/*.{ts,tsx}'

  typecheck-ts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/ts-deps
    - run: pnpm typecheck

  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/python-deps
    - run: uv run pytest
  test-ts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/ts-deps
    - run: pnpm playwright install chromium-headless-shell
    - run: pnpm test
